version: '3'

services:
  viewer:
     build:
       context: .
       dockerfile: Dockerfile
     volumes:
       - ./package.json:/var/lib/eventkit/package.json
       - ./webpack.config.js:/var/lib/eventkit/webpack.config.js
       - ./app:/var/lib/eventkit/app:ro
       - ./static:/var/lib/eventkit/static:ro
       - ./index.html:/var/lib/eventkit/index.html:ro
       - ./build:/var/lib/eventkit/build
     ports:
        - "7080:7080"


