
const types = {
    CLOSED_DRAWER: 'CLOSED_DRAWER',
    OPENED_DRAWER: 'OPENED_DRAWER',
    LAYER_SHOWN:   'LAYER_SHOWN',
    LAYER_HIDDEN:  'LAYER_HIDDEN',
    LAYER_LOADED:  'LAYER_LOADED',
}

export default types
