
const types = {
    CLOSED_DRAWER: 'CLOSED_DRAWER',
    OPENED_DRAWER: 'OPENED_DRAWER',
    FILE_PROCESSING: 'FILE_PROCESSING',
    TABLE_PROCESSED: 'TABLE_PROCESSED',
    FILE_PROCESSED: 'FILE_PROCESSED',
    FILE_ERROR: 'FILE_ERROR',
    FILE_RESET: 'FILE_RESET',
}

export default types
